{
  "patcher": {
    "fileversion": 1,
    "appversion": {
      "major": 9,
      "minor": 0,
      "revision": 0,
      "architecture": "x64",
      "modernui": 1
    },
    "classnamespace": "box",
    "rect": [
      100,
      100,
      640,
      360
    ],
    "bglocked": 0,
    "openrect": [
      0,
      0,
      0,
      0
    ],
    "openinpresentation": 0,
    "default_fontsize": 12,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 2,
    "gridsize": [
      15,
      15
    ],
    "gridsnaponopen": 0,
    "objectsnaponopen": 1,
    "statusbarvisible": 2,
    "toolbarvisible": 2,
    "lefttoolbarpinned": 0,
    "toptoolbarpinned": 0,
    "righttoolbarpinned": 0,
    "bottomtoolbarpinned": 0,
    "toolbars_unpinned_last_save": 0,
    "tallnewobj": 0,
    "boxanimatetime": 200,
    "enablehscroll": 1,
    "enablevscroll": 1,
    "devicewidth": 0,
    "title": "Generated In Max",
    "description": "Patch generated inside Max by node.script + maxforge",
    "digest": "",
    "tags": "",
    "style": "",
    "subpatcher_template": "",
    "assistshowspatchername": 0,
    "boxes": [
      {
        "box": {
          "id": "obj-title",
          "maxclass": "comment",
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            60,
            60,
            200,
            20
          ],
          "text": "Generated by maxforge inside Max via node.script -> thispatcher"
        }
      },
      {
        "box": {
          "id": "obj-hello",
          "maxclass": "message",
          "numinlets": 2,
          "numoutlets": 1,
          "patching_rect": [
            60,
            115,
            80,
            22
          ],
          "outlettype": [
            ""
          ],
          "text": "hello from generated maxforge DSL"
        }
      },
      {
        "box": {
          "id": "obj-printer",
          "maxclass": "newobj",
          "numinlets": 1,
          "numoutlets": 0,
          "patching_rect": [
            60,
            170,
            80,
            22
          ],
          "text": "print maxforge-generated"
        }
      }
    ],
    "lines": [
      {
        "patchline": {
          "source": [
            "obj-hello",
            0
          ],
          "destination": [
            "obj-printer",
            0
          ]
        }
      }
    ]
  }
}